version: '1.0'

services:
  node-app:
    image:
      chintan9925/mern_api
    ports:
      - "4000:4000"
  react-app:
    image: 
      chintan9925/mern_client 
    ports:
      - "3000:3000"
    depends_on:
      - node-app
